from __future__ import annotations
from typing import Sequence, Protocol, runtime_checkable
from discord import RawMessageDeleteEvent

@runtime_checkable
class Instance(Protocol):
    async def sync(self) -> bool: ...
    async def ensure(self) -> bool: ...
    async def repair(self) -> bool: ...
    async def send(self) -> bool: ...
    async def update(self) -> bool: ...
    async def clean(self)-> bool: ...
    async def delete(self) -> bool: ...
    async def on_message_delete(self, payload: RawMessageDeleteEvent) -> bool: ...

type Instances = Sequence[Instance]